# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ivSweeper.ui'
#
# Created: Tue May 06 15:34:47 2014
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_IVSweeper(object):
    def setupUi(self, IVSweeper):
        IVSweeper.setObjectName(_fromUtf8("IVSweeper"))
        IVSweeper.resize(622, 515)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(IVSweeper.sizePolicy().hasHeightForWidth())
        IVSweeper.setSizePolicy(sizePolicy)
        self.centralwidget = QtGui.QWidget(IVSweeper)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.addressGroup = QtGui.QGroupBox(self.centralwidget)
        self.addressGroup.setGeometry(QtCore.QRect(10, 0, 281, 50))
        self.addressGroup.setToolTip(_fromUtf8(""))
        self.addressGroup.setStatusTip(_fromUtf8(""))
        self.addressGroup.setAutoFillBackground(False)
        self.addressGroup.setObjectName(_fromUtf8("addressGroup"))
        self.instrumentCombo = QtGui.QComboBox(self.addressGroup)
        self.instrumentCombo.setGeometry(QtCore.QRect(10, 20, 260, 20))
        self.instrumentCombo.setObjectName(_fromUtf8("instrumentCombo"))
        self.instrumentCombo.addItem(_fromUtf8(""))
        self.sweepButton = QtGui.QPushButton(self.centralwidget)
        self.sweepButton.setEnabled(False)
        self.sweepButton.setGeometry(QtCore.QRect(520, 430, 90, 30))
        self.sweepButton.setCheckable(False)
        self.sweepButton.setAutoDefault(False)
        self.sweepButton.setObjectName(_fromUtf8("sweepButton"))
        self.terminalsGroup = QtGui.QGroupBox(self.centralwidget)
        self.terminalsGroup.setGeometry(QtCore.QRect(300, 0, 150, 50))
        self.terminalsGroup.setObjectName(_fromUtf8("terminalsGroup"))
        self.frontRadio = QtGui.QRadioButton(self.terminalsGroup)
        self.frontRadio.setGeometry(QtCore.QRect(10, 20, 60, 20))
        self.frontRadio.setChecked(True)
        self.frontRadio.setObjectName(_fromUtf8("frontRadio"))
        self.rearRadio = QtGui.QRadioButton(self.terminalsGroup)
        self.rearRadio.setGeometry(QtCore.QRect(80, 20, 60, 20))
        self.rearRadio.setObjectName(_fromUtf8("rearRadio"))
        self.wiresGroup = QtGui.QGroupBox(self.centralwidget)
        self.wiresGroup.setGeometry(QtCore.QRect(430, 50, 180, 50))
        self.wiresGroup.setObjectName(_fromUtf8("wiresGroup"))
        self.twowireRadio = QtGui.QRadioButton(self.wiresGroup)
        self.twowireRadio.setGeometry(QtCore.QRect(10, 10, 91, 40))
        self.twowireRadio.setChecked(True)
        self.twowireRadio.setObjectName(_fromUtf8("twowireRadio"))
        self.fourwireRadio = QtGui.QRadioButton(self.wiresGroup)
        self.fourwireRadio.setGeometry(QtCore.QRect(100, 10, 80, 40))
        self.fourwireRadio.setObjectName(_fromUtf8("fourwireRadio"))
        self.sweepGroup = QtGui.QGroupBox(self.centralwidget)
        self.sweepGroup.setGeometry(QtCore.QRect(10, 100, 390, 130))
        self.sweepGroup.setStatusTip(_fromUtf8(""))
        self.sweepGroup.setObjectName(_fromUtf8("sweepGroup"))
        self.label = QtGui.QLabel(self.sweepGroup)
        self.label.setGeometry(QtCore.QRect(10, 20, 41, 20))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.sweepGroup)
        self.label_2.setGeometry(QtCore.QRect(10, 50, 41, 20))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.reverseButton = QtGui.QPushButton(self.sweepGroup)
        self.reverseButton.setGeometry(QtCore.QRect(10, 90, 111, 30))
        self.reverseButton.setObjectName(_fromUtf8("reverseButton"))
        self.endSpin = QtGui.QSpinBox(self.sweepGroup)
        self.endSpin.setGeometry(QtCore.QRect(50, 50, 91, 20))
        self.endSpin.setMinimum(-20000)
        self.endSpin.setMaximum(20000)
        self.endSpin.setProperty("value", 1000)
        self.endSpin.setObjectName(_fromUtf8("endSpin"))
        self.startSpin = QtGui.QSpinBox(self.sweepGroup)
        self.startSpin.setGeometry(QtCore.QRect(50, 20, 91, 20))
        self.startSpin.setMinimum(-20000)
        self.startSpin.setMaximum(20000)
        self.startSpin.setProperty("value", -1000)
        self.startSpin.setObjectName(_fromUtf8("startSpin"))
        self.totalPointsSpin = QtGui.QSpinBox(self.sweepGroup)
        self.totalPointsSpin.setGeometry(QtCore.QRect(230, 20, 71, 20))
        self.totalPointsSpin.setAccelerated(False)
        self.totalPointsSpin.setSuffix(_fromUtf8(""))
        self.totalPointsSpin.setMinimum(1)
        self.totalPointsSpin.setMaximum(2000)
        self.totalPointsSpin.setProperty("value", 100)
        self.totalPointsSpin.setObjectName(_fromUtf8("totalPointsSpin"))
        self.label_3 = QtGui.QLabel(self.sweepGroup)
        self.label_3.setGeometry(QtCore.QRect(150, 20, 81, 20))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_6 = QtGui.QLabel(self.sweepGroup)
        self.label_6.setGeometry(QtCore.QRect(150, 50, 71, 20))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.autoAdvance = QtGui.QCheckBox(self.sweepGroup)
        self.autoAdvance.setEnabled(False)
        self.autoAdvance.setGeometry(QtCore.QRect(130, 110, 131, 20))
        self.autoAdvance.setObjectName(_fromUtf8("autoAdvance"))
        self.deltaStep = QtGui.QLabel(self.sweepGroup)
        self.deltaStep.setGeometry(QtCore.QRect(310, 20, 81, 20))
        self.deltaStep.setObjectName(_fromUtf8("deltaStep"))
        self.maxPowerCheck = QtGui.QCheckBox(self.sweepGroup)
        self.maxPowerCheck.setGeometry(QtCore.QRect(130, 90, 111, 20))
        self.maxPowerCheck.setObjectName(_fromUtf8("maxPowerCheck"))
        self.delaySpinBox = QtGui.QDoubleSpinBox(self.sweepGroup)
        self.delaySpinBox.setGeometry(QtCore.QRect(230, 50, 71, 20))
        self.delaySpinBox.setDecimals(3)
        self.delaySpinBox.setMaximum(1000.0)
        self.delaySpinBox.setSingleStep(0.01)
        self.delaySpinBox.setProperty("value", 0.02)
        self.delaySpinBox.setObjectName(_fromUtf8("delaySpinBox"))
        self.totalLabel = QtGui.QLabel(self.sweepGroup)
        self.totalLabel.setGeometry(QtCore.QRect(310, 50, 81, 20))
        self.totalLabel.setObjectName(_fromUtf8("totalLabel"))
        self.daqGroup = QtGui.QGroupBox(self.centralwidget)
        self.daqGroup.setGeometry(QtCore.QRect(410, 100, 200, 131))
        self.daqGroup.setObjectName(_fromUtf8("daqGroup"))
        self.zeroCheck = QtGui.QCheckBox(self.daqGroup)
        self.zeroCheck.setGeometry(QtCore.QRect(10, 110, 80, 22))
        self.zeroCheck.setObjectName(_fromUtf8("zeroCheck"))
        self.speedCombo = QtGui.QComboBox(self.daqGroup)
        self.speedCombo.setGeometry(QtCore.QRect(80, 50, 110, 20))
        self.speedCombo.setObjectName(_fromUtf8("speedCombo"))
        self.speedCombo.addItem(_fromUtf8(""))
        self.speedCombo.addItem(_fromUtf8(""))
        self.speedCombo.addItem(_fromUtf8(""))
        self.speedCombo.addItem(_fromUtf8(""))
        self.label_7 = QtGui.QLabel(self.daqGroup)
        self.label_7.setGeometry(QtCore.QRect(10, 50, 62, 20))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.averageSpin = QtGui.QSpinBox(self.daqGroup)
        self.averageSpin.setEnabled(True)
        self.averageSpin.setGeometry(QtCore.QRect(130, 80, 60, 20))
        self.averageSpin.setMinimum(0)
        self.averageSpin.setMaximum(100)
        self.averageSpin.setObjectName(_fromUtf8("averageSpin"))
        self.label_8 = QtGui.QLabel(self.daqGroup)
        self.label_8.setGeometry(QtCore.QRect(10, 80, 121, 20))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.saveModeCombo = QtGui.QComboBox(self.daqGroup)
        self.saveModeCombo.setGeometry(QtCore.QRect(110, 20, 80, 20))
        self.saveModeCombo.setObjectName(_fromUtf8("saveModeCombo"))
        self.saveModeCombo.addItem(_fromUtf8(""))
        self.saveModeCombo.addItem(_fromUtf8(""))
        self.label_10 = QtGui.QLabel(self.daqGroup)
        self.label_10.setGeometry(QtCore.QRect(10, 20, 90, 20))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.complianceGroup = QtGui.QGroupBox(self.centralwidget)
        self.complianceGroup.setGeometry(QtCore.QRect(190, 50, 230, 50))
        self.complianceGroup.setObjectName(_fromUtf8("complianceGroup"))
        self.complianceSpin = QtGui.QSpinBox(self.complianceGroup)
        self.complianceSpin.setGeometry(QtCore.QRect(120, 20, 90, 20))
        self.complianceSpin.setMinimum(1)
        self.complianceSpin.setMaximum(1000)
        self.complianceSpin.setProperty("value", 10)
        self.complianceSpin.setObjectName(_fromUtf8("complianceSpin"))
        self.label_9 = QtGui.QLabel(self.complianceGroup)
        self.label_9.setGeometry(QtCore.QRect(10, 20, 90, 20))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.modeGroup = QtGui.QGroupBox(self.centralwidget)
        self.modeGroup.setGeometry(QtCore.QRect(10, 50, 170, 50))
        self.modeGroup.setObjectName(_fromUtf8("modeGroup"))
        self.sourceVRadio = QtGui.QRadioButton(self.modeGroup)
        self.sourceVRadio.setEnabled(True)
        self.sourceVRadio.setGeometry(QtCore.QRect(10, 20, 60, 22))
        self.sourceVRadio.setChecked(True)
        self.sourceVRadio.setObjectName(_fromUtf8("sourceVRadio"))
        self.sourceIRadio = QtGui.QRadioButton(self.modeGroup)
        self.sourceIRadio.setEnabled(True)
        self.sourceIRadio.setGeometry(QtCore.QRect(90, 20, 70, 22))
        self.sourceIRadio.setObjectName(_fromUtf8("sourceIRadio"))
        self.progress = QtGui.QProgressBar(self.centralwidget)
        self.progress.setGeometry(QtCore.QRect(10, 430, 510, 30))
        self.progress.setProperty("value", 0)
        self.progress.setInvertedAppearance(False)
        self.progress.setObjectName(_fromUtf8("progress"))
        self.sweepContinuallyGroup = QtGui.QGroupBox(self.centralwidget)
        self.sweepContinuallyGroup.setGeometry(QtCore.QRect(10, 230, 390, 70))
        self.sweepContinuallyGroup.setCheckable(True)
        self.sweepContinuallyGroup.setChecked(False)
        self.sweepContinuallyGroup.setObjectName(_fromUtf8("sweepContinuallyGroup"))
        self.label_4 = QtGui.QLabel(self.sweepContinuallyGroup)
        self.label_4.setGeometry(QtCore.QRect(10, 10, 120, 20))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.scanRecoverySpin = QtGui.QDoubleSpinBox(self.sweepContinuallyGroup)
        self.scanRecoverySpin.setGeometry(QtCore.QRect(130, 10, 81, 20))
        self.scanRecoverySpin.setMaximum(1000000000.0)
        self.scanRecoverySpin.setObjectName(_fromUtf8("scanRecoverySpin"))
        self.label_5 = QtGui.QLabel(self.sweepContinuallyGroup)
        self.label_5.setGeometry(QtCore.QRect(10, 40, 120, 20))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.nSweepSpin = QtGui.QSpinBox(self.sweepContinuallyGroup)
        self.nSweepSpin.setGeometry(QtCore.QRect(130, 40, 81, 20))
        self.nSweepSpin.setMaximum(99999)
        self.nSweepSpin.setProperty("value", 100)
        self.nSweepSpin.setObjectName(_fromUtf8("nSweepSpin"))
        self.label_11 = QtGui.QLabel(self.sweepContinuallyGroup)
        self.label_11.setGeometry(QtCore.QRect(220, 10, 111, 20))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.comboBox = QtGui.QComboBox(self.sweepContinuallyGroup)
        self.comboBox.setEnabled(False)
        self.comboBox.setGeometry(QtCore.QRect(330, 10, 50, 22))
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.checkBox = QtGui.QCheckBox(self.sweepContinuallyGroup)
        self.checkBox.setEnabled(False)
        self.checkBox.setGeometry(QtCore.QRect(220, 40, 170, 17))
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(410, 230, 200, 70))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.shutterButton = QtGui.QPushButton(self.groupBox)
        self.shutterButton.setEnabled(True)
        self.shutterButton.setGeometry(QtCore.QRect(100, 30, 91, 30))
        self.shutterButton.setObjectName(_fromUtf8("shutterButton"))
        self.displayBlankCheck = QtGui.QCheckBox(self.groupBox)
        self.displayBlankCheck.setGeometry(QtCore.QRect(10, 50, 91, 20))
        self.displayBlankCheck.setObjectName(_fromUtf8("displayBlankCheck"))
        self.outputCheck = QtGui.QCheckBox(self.groupBox)
        self.outputCheck.setGeometry(QtCore.QRect(10, 30, 91, 20))
        self.outputCheck.setObjectName(_fromUtf8("outputCheck"))
        self.livePlotCheck = QtGui.QCheckBox(self.groupBox)
        self.livePlotCheck.setEnabled(False)
        self.livePlotCheck.setGeometry(QtCore.QRect(10, 10, 91, 20))
        self.livePlotCheck.setObjectName(_fromUtf8("livePlotCheck"))
        self.groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(460, 0, 150, 50))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.deviceAreaEdit = QtGui.QLineEdit(self.groupBox_2)
        self.deviceAreaEdit.setGeometry(QtCore.QRect(40, 20, 71, 20))
        self.deviceAreaEdit.setObjectName(_fromUtf8("deviceAreaEdit"))
        self.groupBox_3 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 300, 600, 60))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.dirEdit = QtGui.QLineEdit(self.groupBox_3)
        self.dirEdit.setGeometry(QtCore.QRect(90, 20, 501, 30))
        self.dirEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dirEdit.setObjectName(_fromUtf8("dirEdit"))
        self.browseButton = QtGui.QPushButton(self.groupBox_3)
        self.browseButton.setGeometry(QtCore.QRect(10, 20, 75, 30))
        self.browseButton.setObjectName(_fromUtf8("browseButton"))
        self.groupBox_4 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 360, 601, 60))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.fileEdit = QtGui.QLineEdit(self.groupBox_4)
        self.fileEdit.setGeometry(QtCore.QRect(10, 20, 580, 30))
        self.fileEdit.setObjectName(_fromUtf8("fileEdit"))
        IVSweeper.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(IVSweeper)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 622, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuGreyRules = QtGui.QMenu(self.menubar)
        self.menuGreyRules.setObjectName(_fromUtf8("menuGreyRules"))
        IVSweeper.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(IVSweeper)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        IVSweeper.setStatusBar(self.statusbar)
        self.actionQuit = QtGui.QAction(IVSweeper)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.actionRun_Test_Code = QtGui.QAction(IVSweeper)
        self.actionRun_Test_Code.setObjectName(_fromUtf8("actionRun_Test_Code"))
        self.menuGreyRules.addAction(self.actionRun_Test_Code)
        self.menuGreyRules.addAction(self.actionQuit)
        self.menubar.addAction(self.menuGreyRules.menuAction())

        self.retranslateUi(IVSweeper)
        self.speedCombo.setCurrentIndex(0)
        self.saveModeCombo.setCurrentIndex(1)
        QtCore.QObject.connect(self.actionQuit, QtCore.SIGNAL(_fromUtf8("triggered()")), IVSweeper.close)
        QtCore.QMetaObject.connectSlotsByName(IVSweeper)

    def retranslateUi(self, IVSweeper):
        IVSweeper.setWindowTitle(_translate("IVSweeper", "IV Sweep Dynamics Investigator", None))
        self.addressGroup.setTitle(_translate("IVSweeper", "Instrument Selection", None))
        self.instrumentCombo.setItemText(0, _translate("IVSweeper", "(Re)Scan for Instruments", None))
        self.sweepButton.setText(_translate("IVSweeper", "Start Sweep", None))
        self.terminalsGroup.setTitle(_translate("IVSweeper", "Output Terminals", None))
        self.frontRadio.setToolTip(_translate("IVSweeper", "Use the terminals on the front of the device", None))
        self.frontRadio.setText(_translate("IVSweeper", "Front", None))
        self.rearRadio.setToolTip(_translate("IVSweeper", "Use the terminals on the rear of the device", None))
        self.rearRadio.setText(_translate("IVSweeper", "Rear", None))
        self.wiresGroup.setTitle(_translate("IVSweeper", "Measurement Type", None))
        self.twowireRadio.setToolTip(_translate("IVSweeper", "Measure voltage across the INPUT/OUTPUT terminals", None))
        self.twowireRadio.setText(_translate("IVSweeper", "Two Wire", None))
        self.fourwireRadio.setToolTip(_translate("IVSweeper", "Measure voltage across the 4-WIRE SENSE terminals", None))
        self.fourwireRadio.setText(_translate("IVSweeper", "Four Wire", None))
        self.sweepGroup.setTitle(_translate("IVSweeper", "Sweep Setup", None))
        self.label.setText(_translate("IVSweeper", "Start:", None))
        self.label_2.setText(_translate("IVSweeper", "End:", None))
        self.reverseButton.setText(_translate("IVSweeper", "Reverse Direction", None))
        self.endSpin.setSuffix(_translate("IVSweeper", " mV", None))
        self.startSpin.setSuffix(_translate("IVSweeper", " mV", None))
        self.label_3.setText(_translate("IVSweeper", "Sweep Points:", None))
        self.label_6.setText(_translate("IVSweeper", "Step Delay:", None))
        self.autoAdvance.setToolTip(_translate("IVSweeper", "a robot chooses when to advance to the next sweep step", None))
        self.autoAdvance.setText(_translate("IVSweeper", "Intelligent Advance", None))
        self.deltaStep.setText(_translate("IVSweeper", "Δ=20 mV", None))
        self.maxPowerCheck.setToolTip(_translate("IVSweeper", "<html><head/><body><p>DANGER: This is relatively untested and there\'s no guarentee it won\'t destroy your device. Make sure your compliance is set to prevent destruction.</p></body></html>", None))
        self.maxPowerCheck.setText(_translate("IVSweeper", "Dwell @ Max Power", None))
        self.delaySpinBox.setToolTip(_translate("IVSweeper", "After reaching a new source value in the sweep, this amount of time will pass before advancing to the next value", None))
        self.delaySpinBox.setSuffix(_translate("IVSweeper", " s", None))
        self.totalLabel.setText(_translate("IVSweeper", "tot=2.000s", None))
        self.daqGroup.setTitle(_translate("IVSweeper", "Data Acquisition Settings", None))
        self.zeroCheck.setToolTip(_translate("IVSweeper", "Theoretically improves accuracy at the expense of speed", None))
        self.zeroCheck.setText(_translate("IVSweeper", "Auto Zero", None))
        self.speedCombo.setToolTip(_translate("IVSweeper", "<html><head/><body><p>Set integration period for a single data point</p><p>• FAST — Sets speed to 0.01 PLC and sets display resolution to 3½ digits.</p><p>• MED — Sets speed to 0.10 PLC and sets display resolution to 4½ digits.</p><p>• NORMAL — Sets speed to 1.00 PLC and sets display resolution to 5½ digits.</p><p>• HI ACCURACY — Sets speed to 10.00 PLC and sets display resolution to 6½</p><p>digits.</p></body></html>", None))
        self.speedCombo.setItemText(0, _translate("IVSweeper", "Fast", None))
        self.speedCombo.setItemText(1, _translate("IVSweeper", "Medium", None))
        self.speedCombo.setItemText(2, _translate("IVSweeper", "Normal", None))
        self.speedCombo.setItemText(3, _translate("IVSweeper", "High Accuracy", None))
        self.label_7.setText(_translate("IVSweeper", "Speed:", None))
        self.averageSpin.setToolTip(_translate("IVSweeper", "repeating filter. danger, this *could* smear data between sweep steps, set to zero to disable", None))
        self.label_8.setText(_translate("IVSweeper", "Points to average:", None))
        self.saveModeCombo.setItemText(0, _translate("IVSweeper", "I,V vs t", None))
        self.saveModeCombo.setItemText(1, _translate("IVSweeper", "I vs V", None))
        self.label_10.setText(_translate("IVSweeper", "Mode:", None))
        self.complianceGroup.setTitle(_translate("IVSweeper", "Compliance and Range", None))
        self.complianceSpin.setToolTip(_translate("IVSweeper", "Set this just above the maximum you expect", None))
        self.complianceSpin.setSuffix(_translate("IVSweeper", " mA", None))
        self.label_9.setText(_translate("IVSweeper", "Plus and minus", None))
        self.modeGroup.setTitle(_translate("IVSweeper", "Source", None))
        self.sourceVRadio.setToolTip(_translate("IVSweeper", "Sweep voltage source", None))
        self.sourceVRadio.setText(_translate("IVSweeper", "Voltage", None))
        self.sourceIRadio.setToolTip(_translate("IVSweeper", "Sweep current source", None))
        self.sourceIRadio.setText(_translate("IVSweeper", "Current", None))
        self.sweepContinuallyGroup.setTitle(_translate("IVSweeper", "Consecutive Sweeps", None))
        self.label_4.setText(_translate("IVSweeper", "Delay Between Scans:", None))
        self.scanRecoverySpin.setSuffix(_translate("IVSweeper", " s", None))
        self.label_5.setText(_translate("IVSweeper", "Number of Sweeps:", None))
        self.label_11.setText(_translate("IVSweeper", "Hold Between Scans:", None))
        self.comboBox.setItemText(0, _translate("IVSweeper", "L=∞", None))
        self.comboBox.setItemText(1, _translate("IVSweeper", "Voc", None))
        self.comboBox.setItemText(2, _translate("IVSweeper", "Jsc", None))
        self.comboBox.setItemText(3, _translate("IVSweeper", "Mppt", None))
        self.checkBox.setText(_translate("IVSweeper", "Toggle Shutter Between Scans", None))
        self.groupBox.setTitle(_translate("IVSweeper", "Miscellaneous", None))
        self.shutterButton.setText(_translate("IVSweeper", "Toggle Shutter", None))
        self.displayBlankCheck.setToolTip(_translate("IVSweeper", "This blanks the Keithley\'s display during measurement, allowing for a slight increase in measurement speed", None))
        self.displayBlankCheck.setText(_translate("IVSweeper", "Blank Display", None))
        self.outputCheck.setText(_translate("IVSweeper", "Output On", None))
        self.livePlotCheck.setText(_translate("IVSweeper", "Live Data View", None))
        self.groupBox_2.setTitle(_translate("IVSweeper", "Device Area [cm^2]", None))
        self.deviceAreaEdit.setToolTip(_translate("IVSweeper", "Enter Device Area Here", None))
        self.deviceAreaEdit.setText(_translate("IVSweeper", "0.12", None))
        self.groupBox_3.setTitle(_translate("IVSweeper", "Output Directory", None))
        self.browseButton.setText(_translate("IVSweeper", "Browse", None))
        self.groupBox_4.setTitle(_translate("IVSweeper", "Output File Name", None))
        self.menuGreyRules.setTitle(_translate("IVSweeper", "File", None))
        self.actionQuit.setText(_translate("IVSweeper", "Quit", None))
        self.actionRun_Test_Code.setText(_translate("IVSweeper", "Run Test Code", None))

